# Generated by Django 5.2.8 on 2025-11-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Manufacture_Date', models.DateField()),
                ('Expire_Date', models.DateField()),
                ('Weight', models.CharField(max_length=10)),
                ('Stock', models.IntegerField()),
                ('Price', models.FloatField()),
            ],
        ),
    ]
